version: '3'
services:
    anaconda:
        build: .
        volumes:
            - ./:/workspace
            - "/Users/myaun/Google Drive File Stream/マイドライブ/Shared_myaunraitau/data/keyakizaka_mining:/keyakizaka_mining"
        ports:
            - "8889:8889"
